Bookme/Bookme/ViewModels/ApplicationUserViewModel.cs
namespace Bookme.ViewModels
{
    public class ApplicationUserViewModel
    {
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? GenderId { get; set; }
        public string PhoneNumber { get; set; }
        public string? Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string UserName { get; set; }
        public string MusicSpecialization { set; get; }
        public string Bio { get; set; }
        public DateTime DateCreated { get; set; }
        public int CategoryId { get; set; }
        public bool IsDeactivated { get; set; }

    }
}

Bookme/Bookme/ViewModels/CategoryViewModel.cs
using Bookme.Models;

namespace Bookme.ViewModels
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public DateTime DateCreated { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public List<Category>? Categories { get; set; }
    }
}

Bookme/Bookme/Controllers/AccountController.cs
using Bookme.Database;
using Bookme.IHelper;
using Microsoft.AspNetCore.Mvc;

namespace Bookme.Controllers
{
    public class AccountController : Controller
    {
             private readonly ApplicationDbContext _context;
             private readonly IUserHelper _userHelper;

        public AccountController(ApplicationDbContext context, IUserHelper userHelper)
        {
            _context = context;
            _userHelper = userHelper;
        }
        [HttpGet]
        public IActionResult Registration()
        {
            ViewBag.Gender = _userHelper.DropDownOfGender();
            ViewBag.Category = _userHelper.DropDownOfCategory();
            return View();
        }
        
        




        public IActionResult Login()
        {
            return View();
        }

    }
}

Bookme/Bookme/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bookme.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bookme/Bookme/Controllers/HomeController.cs
using Bookme.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookme.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bookme/Bookme/Controllers/SuperAdminController.cs
using Bookme.Database;
using Bookme.IHelper;
using Bookme.Models;
using Bookme.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Protocol.Plugins;
using System.ComponentModel.Design;

namespace Bookme.Controllers
{
    public class SuperAdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAdminHelper _adminHelper;

        public SuperAdminController(ApplicationDbContext context, IAdminHelper adminHelper)
        {
            _context = context;
            _adminHelper = adminHelper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Category() 
        {
            var categories = _context.Category.Where(p => p.Active && !p.Deleted).ToList();
            if (categories.Count > 0)
            {
                var cat = new CategoryViewModel
                {
                    Categories = categories,
                };
                return View(cat);
            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(string categoryName)
        {
            if (!string.IsNullOrEmpty(categoryName))
            {
                var check = _context.Category.Where(f => f.Name.ToLower() == categoryName.ToLower() && !f.Deleted).FirstOrDefault();
                if (check != null)
                {
                    return Json(new { isError = true, msg = "Name Already Exists" });
                }

                if (ModelState.IsValid)
                {
                    var model = new Category()
                    {
                        DateCreated = DateTime.Now,
                        Deleted = false,
                        Name = categoryName,
                        Active = true,
                    };

                    _context.Category.Add(model);
                    _context.SaveChanges();
                    return Json(new { isError = false, msg = "Category created successfully" });
                }
                return Json(new { isError = true, msg = "Failed" });
            }
            return Json(new { isError = true, msg = "Failed" });
        }
        [HttpGet]
        public JsonResult GetCategoryToEdit(int categoryId) 
        {
            if (categoryId != 0)
            {
                var category = _adminHelper.GetCategoryById(categoryId);
                if (category != null) 
                {
                    CategoryViewModel categoryView = new CategoryViewModel()
                    {
                        Id = category.Id,
                        Name = category.Name,
                    };
                    return Json(new { isError = false, data = categoryView });
                }
            }
            return Json(new { isError = true, msg = "Error occured" });
        }
        [HttpPost]
        public JsonResult UpdateCategory(string categoryName)
        {
            if (categoryName == null)
            {
                return Json(new { isError = true, msg = "" });
            }
            var data = JsonConvert.DeserializeObject<CategoryViewModel>(categoryName);
            {
               var category = _adminHelper.UpdateCategoryName(data);
                if (category == true)
                {
                    return Json(new { isError = false, msg = "Category updateed successfully" });
                }
            }
            return Json(new { isError = true, msg = "Error occured" });
        }
        public JsonResult DeleteCategory(int id)
        {
            if (id != 0)
            {
                var category = _context.Category.Where(x => x.Id == id && x.Active).FirstOrDefault();
                if (category != null)
                {
                   category.Active = false;
                   category.Deleted = true;
                    _context.Update(category);
                    _context.SaveChanges();
                    return Json(new { isError = false, msg = "Category deleted successfully" });
                }
            }
            return Json(new { isError = true, msg = "Could not find Category" });
        }
    }
}

Bookme/Bookme/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="main">
    <div class="containercontainer-fluid mt-5 ml-0">
        <h1>Welcome Admin !</h1>
        <div class="row">
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 1</h4>
            </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 2</h4>
            </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 3</h4>
            </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 4</h4>
            </div>
        </div>
    </div>
</div>

Bookme/Bookme/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .bookme-image
    {
      background: url(Images/hhh2.jpg) no-repeat center;
      background-size:cover;
      height: 700px;
      position: relative;
    }

    .bookme-logo
    {
        
    }

    .bookme-text
    {
     text-align: center;
     position:absolute;
     top: 40%;
     left: 25%;
     right: 25%
     color: white;
    }

    .bookme-text h1{
        font-weight:700;
        color: white;
    }
</style>

<div class="container-fluid bookme-image">
<div class="">
    <div class="bookme-text">
      <h1 class="display-3" style="font-family: 'Sitka Display'">WELLCOME TO BOOK ME</h1>
      <p class="text-white lead"><b>We are the music makers and we are the dreamers of dreams.<br />
         @*  A creative artist works on his next composition because he was not satisfied with his previous one *@</b></p>
      <a asp-controller="" asp-action="" class="btn btn-light mt-3 p-4"><b>Get Started</b></a>
    </div>
</div>
</div>


@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@

Bookme/Bookme/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookme</title>
    <link rel="stylesheet" href="~/bootstrap-4.6.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookme.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css"/>
    <link rel="stylesheet" href="~/css/sweetalert2.css"/>
    <script>

    function showLoader() {
        $("#myModal").modal({ backdrop: 'static', keyboard: false });
    }
    function hideLoader() {
        $("#myModal").modal('hide');
    }
    function showSpin() {
        $("#showspin").fadeOut(1500);
        $("#showcontent").fadeIn(3000);
    }

    function errorAlert(message) {
        Swal.fire({
            icon: 'error',
            text: message,
        })
    }

    function infoAlert(message) {
        Swal.fire({
            icon: 'info',
            text: message,
        })
    }

    function infoAlertWithStyles(message) {
        Swal.fire({
            title: 'Notification',
            icon: 'info',
            text: message,
        })
    }

    function successAlert(message) {
        Swal.fire({
            icon: 'success',
            text: message,
        })
    }

    function newSuccessAlert(message, url) {
        Swal.fire({
            icon: 'success',
            text: message,
        }).then(function () {

            location.href = url;
        })
    }

    function successAlertWithRedirect(message, url) {
        swal.fire({
            title: "Success",
            text: message,
            icon: "success",
            timer: "30000",
            overlay: "background - color: rgba(43, 165, 137, 0.45)",
        }).then(function () {

            location.href = url;
        })
    }

    function successAlertWithDoubleButtons(message, url) {
        swal.fire({
            title: "Success",
            text: message,
            icon: "success",
            showCancelButton: true,
            cancelButtonColor: "#22c8db",
            confirmButtonText: "Pay Reg Bonus",
            confirmButtonColor: "#006400",
        }).then((result) => {
            if (result.isConfirmed) {
                location.href = url;
            }
            else {
                location.reload();
            }
        })
    }

</script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow" style="background-color: #f2f2f2">
            <div class="container-fluid">
                <a class="navbar-brand text-black" style="font-size:100%" asp-area="" asp-controller="SuperAdmin" asp-action="Index">Bookme</a>
                <a class="navbar-brand text-black" id="slideToggle" style="font-size:150%"><i class="fa fa-bars"></i></a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               @*  <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"></button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" asp-action="" asp-controller="">My profile</a>
                                <a class="dropdown-item" asp-action="" asp-controller="">Logout</a>
                            </div>
                        </div>
                    </ul>
                </div> *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle btn btn-primary text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">My profile</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div id="sideBar" class="sidenav shadow" style="background-color:#f2f2f2">
        <ul>
            <li>
                <a class="nav-link text-dark" asp-action="Index" asp-controller="SuperAdmin">Dashboard</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-action="Category" asp-controller="SuperAdmin">Category</a>
            </li>
            <li>
                <a class="nav-link text-dark" asp-action="Profile" asp-controller="SuperAdmin">Profile</a>
            </li>

        </ul>
    </div>


    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bookme - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@*     <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    <script src="~/lib/jquery/dist/jquery-3.3.1.min.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>
    @*  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script> *@
    <script src="~/bootstrap-4.6.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/bootstrap-4.6.2-dist/js/bootstrap.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $("#slideToggle").click(function () {
                $("#sideBar").slideToggle("slow");
            });
        });
    </script>
</body>
</html>

Bookme/Bookme/Views/Shared/_DeleteCategory.cshtml
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body">
            <div class="form-header">
                <h3 class="text-center">Delete Category</h3>
                <p class="text-center">Are you sure you want to delete?</p>
            </div>
            <div class="modal-btn delete-action">
                <div class="row">
                    <input class="form-control" type="text" id="deleteCategoryId" hidden>
                    <div class="col-6 text-right">
                        <a class="btn btn-danger continue-btn" href="javascript:void(0);" onclick="SaveCategoryDetails()">
                            Delete
                        </a>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-primary cancel-btn" href="javascript:void(0);" data-dismiss="modal"> cancel </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bookme/Bookme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookme</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookme.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow" style="background-color: #f2f2f2">
            <div class="container-fluid">
                <a class="navbar-brand text-black" style="font-size:200%" asp-area="" asp-controller="Home" asp-action="Index">Bookme</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Account" asp-action="Registration">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" style="font-size:larger" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bookme - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
 *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bookme/Bookme/Views/SuperAdmin/Category.cshtml
@model Bookme.ViewModels.CategoryViewModel
@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    body {
        counter-reset: Serial;
    }

     tr td:first-child::before {
         counter-increment: Serial;
        content: counter(Serial);
    }
</style>
<div id="main">
    <div class="container-fluid">
        <div class="row p-4">
            <div class="col-6">
                <h2 class="text-primary">Category List</h2>
            </div>
            <div class="col-6 text-right">
                <a class="btn btn-primary" data-toggle="modal" data-target="#addCategory">
                    <i class="fa fa-plus"></i> &nbsp;  Create New Category
                </a>
            </div>
        </div>

    </div>
     <div class="container p-3">
        
        <br /><br />

        @if (Model != null || Model?.Categories.Count() > 0)
        {
            //add datatable
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            SN</th>
                        <th>
                            Category Name
                        </th>
                        <th>
                            Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model?.Categories)
                    {
                        <tr>
                            <td></td>
                            <td width="50%">@category.Name</td>
                            <td width="20%" class="text-center">
                                <div class="w-75 btn-group" role="group">
                                    <a class="btn btn-primary mx-2" data-toggle="modal" data-target="#editCategory" onclick="getCategoryDetails('@category.Id')">
                                        <i class="fa fa-pen-to-square"></i></a>
                                    <a class="btn btn-danger mx-2" data-toggle="modal" data-target="#deleteCategory" onclick="categoryToDelete('@category.Id')">
                                        <i class="fa fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>

            </table>
        }
        else
        {
            <p> No Category exists.</p>
        }
    </div>
</div>

<div class="modal fade" id="addCategory" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> <b> Add new Category </b> </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        
                        <label class="col-form-label"> Name </label>
                        <input class="form-control" type="text" id="name" required>
                    </div>
                </div>

                <div class="col-sm-6 m-auto">
                    <div class="mt-3">
                        <button type="button" class="btn btn-outline-primary d-block mx-auto px-4 py-2"
                                id="submit_Btn" style="border-radius: 20px;" onclick="SaveCategoryDetails()">
                            Submit
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editCategory" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> <b> Edit Category </b> </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">

                        <label class="col-form-label"> Name </label>
                        <input class="form-control" type="text" id="categoryName" required>
                        <input class="form-control" type="text" id="categoryId" hidden>
                    </div>
                </div>

                <div class="col-sm-6 m-auto">
                    <div class="mt-3">
                        <button type="button" class="btn btn-outline-primary d-block mx-auto px-4 py-2"
                                id="submit_Btn" style="border-radius: 20px;" onclick="EditCategoryDetails()">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal custom-modal fade" id="deleteCategory" role="dialog">
   @*  @Html.Partial("_DeleteCategory") *@
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header">
                    <h3 class="text-center">Delete Category</h3>
                    <p class="text-center">Are you sure you want to delete?</p>
                </div>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <input class="form-control" type="text" id="deleteCategoryId" hidden>
                        <div class="col-6 text-right">
                            <a class="btn btn-danger continue-btn" href="javascript:void(0);" onclick="deleteCategoryDetails()">
                                Delete
                            </a>
                        </div>
                        <div class="col-6">
                            <a class="btn btn-primary cancel-btn" href="javascript:void(0);" data-dismiss="modal"> cancel </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bookme/Bookme/Views/SuperAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="main">
    <div class="containercontainer-fluid mt-5 ml-0">
        <h1>Welcome SuperAdmin !</h1>
        <div class="row">
            <div class="card col-2 mx-3 mt-2">
              <h4>Category 1</h4>
          </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 2</h4>
            </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 3</h4>
            </div>
            <div class="card col-2 mx-3 mt-2">
                <h4>Category 4</h4>
            </div>
        </div>
          <div class="row">
            <div class="card col-2 mx-3 mt-3">
                <h4>Category 5</h4>
            </div>
            <div class="card col-2 mx-3 mt-3">
                <h4>Category 6</h4>
            </div>
            <div class="card col-2 mx-3 mt-3">
                <h4>Category 7</h4>
            </div>
          </div>
            <div class="">
                <div class="bookme-text">
                    <h4 class="display-3 text-black" style="font-family: 'Sitka Display'">WELCOME TO BOOK ME</h4>
                    <p class=" lead">
                        <b>
                            We are the music makers and we are the dreamers of dreams.<br />
                        </b>
                    </p>
                    <a asp-controller="" asp-action="" class="btn btn-light mt-3 p-4"><b>Get Started</b></a>
                </div>
            </div>
    </div>
</div>